### PR TITLE
Update LegacyCameraConnectionFragment.java

### PR DESCRIPTION
**Pull request by shengjunhu**
[UPDATE] for camera open and close on TextureSurfaceListener(), If have any problem,  please commit logs to this respository

### CODE REVIEW

**Review by Sanjay2802 — APPROVED** [review]

**Comment by Sanjay2802** [comment]
Getting log: 

 D/LegacyCameraConnectionFragment: openCamera(..) start working

But no preview still, 

But at first time when I merged code ,preview came , but later never previewed

**Comment by Sanjay2802** [comment]
Entire Log:

`2022-11-16 22:58:23.757 28130-28130/com.jiangdg.usbcamera D/tensorflow: CameraActivity: onResume org.tensorflow.lite.examples.detection.DetectorActivity@350a858

2022-11-16 22:58:23.760 28130-28130/com.jiangdg.usbcamera E/LegacyCameraConnectionFragment: onResume()

2022-11-16 22:58:23.794 28130-28130/com.jiangdg.usbcamera D/LegacyCameraConnectionFragment: openCamera(..)

2022-11-16 22:58:23.835 28130-28130/com.jiangdg.usbcamera E/UsbCamera: [28130*UsbCamera.cpp:54:connectDevice]:uvc_init(): 0

2022-11-16 22:58:23.821 28130-28130/com.jiangdg.usbcamera W/angdg.usbcamera: type=1400 audit(0.0:521025): avc: denied { read } for name="usb" dev="tmpfs" ino=29819167 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=0 app=com.jiangdg.usbcamera

2022-11-16 22:58:23.821 28130-28130/com.jiangdg.usbcamera W/angdg.usbcamera: type=1400 audit(0.0:521026): avc: denied { read } for name="/" dev="tmpfs" ino=27839 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0 app=com.jiangdg.usbcamera

2022-11-16 22:58:23.839 28130-28130/com.jiangdg.usbcamera E/UsbCamera: [28130*UsbCamera.cpp:67:connectDevice]:uvc_init(): 12

2022-11-16 22:58:23.854 28130-28130/com.jiangdg.usbcamera D/LegacyCameraConnectionFragment: openCamera(..) start working.

2022-11-16 22:58:23.854 28130-28130/com.jiangdg.usbcamera W/UsbCamera: [28130*UsbCamera.cpp:230:startStream]:startStream: status:14`

**Comment by shengjunhu** [comment]
> Getting log:
> 
> D/LegacyCameraConnectionFragment: openCamera(..) start working
> 
> But no preview still,
> 
> But at first time when I merged code ,preview came , but later never previewed

Please commit all logs on files， and record screen to mp4， I need analysis the scene.

**Comment by shengjunhu** [comment]
> Getting log:
> 
> D/LegacyCameraConnectionFragment: openCamera(..) start working
> 
> But no preview still,
> 
> But at first time when I merged code ,preview came , but later never previewed

I can't understand that but later never previewe of you said. is restart app and never previewed ?

**Comment by Sanjay2802** [comment]
Yesss

**Comment by Sanjay2802** [comment]
[LOG.txt](https://github.com/Sanjay2802/usbc/files/10029830/LOG.txt)


https://user-images.githubusercontent.com/86015315/202409495-26509dde-69a1-4a4c-984a-cc96156a19b9.mp4

**Comment by Sanjay2802** [comment]
now it never previewed, exact log is attached !
everytime i close application i detach usb cam and re attach and start application !!

**Comment by Sanjay2802** [comment]
https://user-images.githubusercontent.com/86015315/202413211-7670548b-0965-4860-b8d7-b17d6bdf19f2.mp4

When I was randomly trying, once it came, then never

**Comment by shengjunhu** [comment]
> [LOG.txt](https://github.com/Sanjay2802/usbc/files/10029830/LOG.txt)
> 
>  document_6318999341801409181.mp4

was previewed ok before 2022-11-17 14:41:57.370 on LOG.txt ?

**Comment by Sanjay2802** [comment]
Noo, not , like this only

**Comment by Sanjay2802** [comment]
[Log when preview is ok.txt](https://github.com/Sanjay2802/usbc/files/10030316/Log.when.preview.is.ok.txt)


the above log is when preview was working and ok

**Comment by shengjunhu** [comment]
> now it never previewed, exact log is attached ! everytime i close application i detach usb cam and re attach and start application !!

There were image to be callback when not previewed.

**Comment by shengjunhu** [comment]
> now it never previewed, exact log is attached ! everytime i close application i detach usb cam and re attach and start application !!

There is a demo apk in the sdk_ usb_camera  library at previously . Can it run normally on Android 13?

I checked the code repeatedly and found no problem, but the log kept reminding me that camera was already working

**Comment by Sanjay2802** [comment]
So confusing (no sleep at night ), now android 11, android 12 also same problem, not working 

Demo.apk is not present in your GitHub repository to check.

Couldn't find where the problem is... Because now it does not work in any device.

**Comment by Sanjay2802** [comment]
[log new.txt](https://github.com/Sanjay2802/usbc/files/10037226/log.new.txt)


log got from new changes

**Comment by shengjunhu** [comment]
> > now it never previewed, exact log is attached ! everytime i close application i detach usb cam and re attach and start application !!
> 
> There is a demo apk in the sdk_ usb_camera library at previously . Can it run normally on Android 13?
> 
> I checked the code repeatedly and found no problem, but the log kept reminding me that camera was already working



> [log new.txt](https://github.com/Sanjay2802/usbc/files/10037226/log.new.txt)
> 
> log got from new changes

Please use adb save log， don't copy.
such as ：adb logcat -v time > D:\log.txt

**Comment by shengjunhu** [comment]
> [log new.txt](https://github.com/Sanjay2802/usbc/files/10037226/log.new.txt)
> 
> log got from new changes

I think the usage is incorrect. It works normally on Android 10, 11 and 12. I don't have Android 13 devices

**Comment by shengjunhu** [comment]
> [log new.txt](https://github.com/Sanjay2802/usbc/files/10037226/log.new.txt)
> 
> log got from new changes

I think the usage is incorrect. It works normally on Android 10, 11 and 12. I don't have Android 13 devices

**Comment by shengjunhu** [comment]
> > > now it never previewed, exact log is attached ! everytime i close application i detach usb cam and re attach and start application !!
> > 
> > 
> > There is a demo apk in the sdk_ usb_camera library at previously . Can it run normally on Android 13?
> > I checked the code repeatedly and found no problem, but the log kept reminding me that camera was already working
> 
> > [log new.txt](https://github.com/Sanjay2802/usbc/files/10037226/log.new.txt)
> > log got from new changes
> 
> Please use adb save log， don't copy. such as ：adb logcat -v time > D:\log.txt

I suggest you first shut down phone and then restart phone,  then use the adb to save the log, and then operate the app, so that you can record a complete log

**Comment by Sanjay2802** [comment]
till what  resolution of usb camera does sdk support ?

**Comment by Sanjay2802** [comment]
brother wait, i suppose its working , till what resolution of usb camera does sdk support ?

**Comment by shengjunhu** [comment]
> till what resolution of usb camera does sdk support ?

https://github.com/shengjunhu/usbc/blob/patch-2/app/src/main/java/org/tensorflow/lite/examples/detection/LegacyCameraConnectionFragment.java#268

UsbCamera.SupportInfo info = supportInfos.get(0);
Select you need resolution ，I suggest you that choice mjpeg of support info, you can foreach ' supportInfos'.

**Comment by Sanjay2802** [comment]
Meanwhile after checking.. Usb camera preview is working on all devices. Just restarted 3 different phones with different os.i suppose some kind of bug it seems 
After the restart of phone, usb cam is normally working, thankyou  very much brother for your help. I won't forget this help at all .

**Pull request closed without merging**
